--require('pretty-fold').ft_setup('c', {
--   matchup_patterns = {
--      { '{', '}' } -- do ... end blocks
--      --{ '^%s*if', 'end' },  -- if ... end
--      --{ '^%s*for', 'end' }, -- for
--      --{ 'function%s*%(', 'end' }, -- 'function( or 'function (''
--      --{  '{', '}' },
--      --{ '%(', ')' }, -- % to escape lua pattern char
--      --{ '%[', ']' }, -- % to escape lua pattern char
--   },
--})
--require('pretty-fold').setup()
