#!/usr/bin/env bash
export $(dbus-launch)

# SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"
# SCRIPTPATH = "/home/dmitrii/.config/leftwm/themes/current"
# SCRIPTPATH="/home/dmitrii/dotfiles/config/leftwm/themes/Ascent"
SCRIPTPATH="$HOME/.config/leftwm/themes/current"

autorandr --change

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
        /tmp/leftwm-theme-down
        rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH/down" /tmp/leftwm-theme-down

# run kanata for key remapping
#kanata -c $SCRIPTPATH/config.kbd &

#boot compton or picom if it exists
#if [ -x "$(command -v compton)" ]; then
#  compton &> /dev/null &
#elif [ -x "$(command -v picom)" ]; then
picom --backend glx &>/dev/null &
#fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
#feh --bg-scale "/home/dmitrii/dotfiles/config/leftwm/themes/Ascent/wallpaper.jpg"
feh --bg-fill "$HOME/.config/leftwm/themes/current/wanderer.jpg"

#boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
        pkill polybar
        monitors="$(polybar -m | sed s/:.*// | tac)"
        while read -r display; do
                MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar &>/dev/null &
        done <<<"$monitors"
        exit 0
fi
