keys:
  - users:
    - &mine age19vefp7y0y8jdc4gcy4l4yq6r4q3a9u2xevj3uy8dnf6v9ak7hfls3hjejc
  - hosts:
    - &mine_laptop age1ggpnjskft839vcjzunmpdwhs9easwxr7cvd350mlqmvptw3aqdnsqpms42
    - &gitea_worker_1 age1glh3xkjqh5a4zxj835g0rxhg8ypdk9ywj3p83557c3e9lleq243s6jvc4r
    - &woodpecker_agent_1 age1zeh3kcd7qqx0g7qgra975ls0u9dwhe64anr0m5lthr0aq73nuu7q6xg9ve
    - &container_registry age1kqasman7j5fguy8xfwkkvz2aad38ugk437enstcz4kg9r8tjeg3q6f5v5c
    - &nginx_local age1xctyl8g4lezw4glhhaggpd8u54vryff5jkwz3e9v4srlgphwe5jqsgsvvw
    - &woodpecker_server age1xxx7z9mn44pagwk46kay5s8ufj37zxf3qat97tgexgkasmljpulszrfann
    - &wakapi age1jwal9267d3tm9azlkprd8lf4vkjytre32pcr2jcflpmruxxn0vfqwupku2
    - &grafana age1cpspdpwe53mqgen6dfkxlhd8892xsxklcpvy9d6typtkvftm2vkqtcysvg
creation_rules:
  - path_regex: etc/nixos/.*\.(yaml)$
    key_groups:
    - age:
      - *mine_laptop
      - *mine
  - path_regex: nix/hosts/gitea_worker/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *gitea_worker_1
  - path_regex: nix/hosts/woodpecker_agent/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *woodpecker_agent_1
  - path_regex: nix/hosts/container_registry/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *container_registry
  - path_regex: nix/hosts/nginx_local/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *nginx_local
  - path_regex: nix/hosts/woodpecker_server/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *woodpecker_server
  - path_regex: nix/hosts/wakapi/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *wakapi
  - path_regex: nix/hosts/grafana/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *grafana
  - path_regex: nix/hosts/backup/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
