keys:
  - keys:
    - &default_c age1yubikey1qvsqtwd2wagjf2fkdmmjxg8wrm6u8mpnh02vmjvqz982djk4elw4czk8nqd
  - users:
    - &mine age19vefp7y0y8jdc4gcy4l4yq6r4q3a9u2xevj3uy8dnf6v9ak7hfls3hjejc
  - hosts:
    - &mine_laptop age1ggpnjskft839vcjzunmpdwhs9easwxr7cvd350mlqmvptw3aqdnsqpms42
    - &gitea_worker_1 age1glh3xkjqh5a4zxj835g0rxhg8ypdk9ywj3p83557c3e9lleq243s6jvc4r
    - &woodpecker_agent_1 age1zeh3kcd7qqx0g7qgra975ls0u9dwhe64anr0m5lthr0aq73nuu7q6xg9ve
    - &registry age178f4qgfgku78khyclpx4lhlcjwez5v8vc854q0hg4ka92xn7xg4qlprntj
    - &nginx_local age1mp994dhmdgh9m9x03wdrjsluksqydy9gn7q6pw0w3ruuglwqaccqw06dtx
    - &woodpecker_server age1xxx7z9mn44pagwk46kay5s8ufj37zxf3qat97tgexgkasmljpulszrfann
    - &wakapi age1jwal9267d3tm9azlkprd8lf4vkjytre32pcr2jcflpmruxxn0vfqwupku2
    - &grafana age1cpspdpwe53mqgen6dfkxlhd8892xsxklcpvy9d6typtkvftm2vkqtcysvg
    - &piwatch age1nlnchf9ye4pcdyau2u6gfwawxdufzsht2v4ur5geldejv9226v0sckyeyd
    - &openobserve age1uxelnfg5wn33jtm8kmmatc7ku6rudmdcg52e86l05ket8jjg3ceq7t0gky
    - &backup age1kepnfdct2up7l9w9e7naqwlmsyrxunhv82kx45m85veu3zfpf9ds2mjhty
creation_rules:
  - path_regex: etc/nixos/.*\.(yaml)$
    key_groups:
    - age:
      - *default_c
      - *mine_laptop
      - *mine
  - path_regex: nix/hosts/gitea_worker/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *gitea_worker_1
  - path_regex: nix/hosts/woodpecker_agent/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *woodpecker_agent_1
  - path_regex: nix/hosts/registry/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *registry
  - path_regex: nix/hosts/nginx_local/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *nginx_local
  - path_regex: nix/hosts/woodpecker_server/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *woodpecker_server
  - path_regex: nix/hosts/wakapi/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *wakapi
  - path_regex: nix/hosts/grafana/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *grafana
  - path_regex: nix/hosts/backup/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *backup
  - path_regex: nix/hosts/piwatch/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *piwatch
  - path_regex: nix/hosts/openobserve/.*\.(yaml)$
    key_groups:
    - age:
      - *mine
      - *openobserve
