keys:
  - users:
    - &mine age19vefp7y0y8jdc4gcy4l4yq6r4q3a9u2xevj3uy8dnf6v9ak7hfls3hjejc
  - hosts:
    - &mine_laptop age1ggpnjskft839vcjzunmpdwhs9easwxr7cvd350mlqmvptw3aqdnsqpms42
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *mine_laptop
      - *mine

