-- local keymap = vim.keymap
-- keymap.amend = require('keymap-amend')

--keymap.amend('n', 'k', function(original)
--   print('k key is amended!')
--   original()
--end)
--keymap.amend(mode, lhs, function(original)
--    -- your custom logic
--    original() -- execute the original 'lhs' mapping
--end, opts)
