wireguard:
    wireguard_ip: ENC[AES256_GCM,data:trWAaV8FfH7us+XNR1k=,iv:vWhMGLb49lANWJqF1YTWor6THj4Ja9ujxtuTHmU3awk=,tag:lbLdg+0NCQx9DVkkx34cuQ==,type:str]
    private_key: ENC[AES256_GCM,data:CAMoDQTKD7pdTx7V0m0yxX0DHBDD/QmBcngMLjqrwKEowQlD04zHpndQ8J4=,iv:EG4KzLG25ZOga0XVAORm1X1xe6SPGKz28RpRd48U6FQ=,tag:Vb4lm8VvhO2PTweO3Rmy7g==,type:str]
    preshared_key: ENC[AES256_GCM,data:HwlrE4ue9eDuTKw/0HSA8kHFzJDVVuspybVlIVlTBQWhwQqLyNqIyVn1IDA=,iv:jaLnG+GPgCotqaTjndNgVw4JRGVXMXPSvlN/uibtTzw=,tag:Eys2Rtj91XHwhoUTjDwpEg==,type:str]
    public_key: ENC[AES256_GCM,data:dmIdmAaFIgSwfZh4UE/c7YiNkZLaJGvPH7aQeSVsHldIIWkFUTUHDOUDP58=,iv:3jMn9EwqvsV1zu+Lm8tJEGacoH/H9lPGiRy4k94Z3iY=,tag:HNzlsNm6rqXZ9pbDVGhqmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19vefp7y0y8jdc4gcy4l4yq6r4q3a9u2xevj3uy8dnf6v9ak7hfls3hjejc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUamp3M04rN1pJY3EyMmE1
            SlZsRnhOMFJNbDVvVlc3NWQ1RmduR0tTdUU0CjB1UUVUZ1FJeXROdkMyNlFaUjg0
            Rk9wbU9sbUxCMWpmNWdrT2tuRmwydGsKLS0tIGVkTHdQVUFBSlUvUEZYU21vaVBX
            V1JFbmtRbnFHZEx0eEVwZVUrMXhObEUKz2VLB3H9AUgaerCf2ut6UoYrX3SVWL5R
            je6OrR4kJTE6S50zvSLS/hSWs9ld2gBXgja5px3dWuTGY9mcm7MPhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cpspdpwe53mqgen6dfkxlhd8892xsxklcpvy9d6typtkvftm2vkqtcysvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVDQ5bDhLcTlFOVNGL1FU
            T1VUQTBpRmcwTUN3WDM3WGhIdGpjMWQyWHpBCnFTMlhrTkxxQXdzMHM5MmdoZW9X
            RWova0lVemFLa0FNdEgwL0hQVTRWVVUKLS0tIGkyVXRDKzkrS3VtQkd0SnZ3VHc2
            eXM1aEpEc2JIOWxZM1VKcjVwZk15SEEKNGbl7jSQL8zqn8i20zLlnvwiAsgU89GN
            Ii63Is72d/wunzXsxx33lfaJVS2EtB+1KmcZNYAuEbjnelKLiqzTwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T00:42:49Z"
    mac: ENC[AES256_GCM,data:uvGQcrCuJFiwVv2H6JMnysUIQRbecv0KpWSGdzGEVOultlXocH3RnPCHMS4VwCtdS+IbDk67HkBQZiizp95r/Co1I450dljTABl7iTNSkmw0BAIE8TbPu1DAJ0ZfVvd3vMsQxwZjA939e5tz9Z4bO+MsHaW18ZoMNB7PCXexOjM=,iv:y++SVCvN6/FeC7naAmk6abc6sBGvLnSkFM4keV/WdmM=,tag:fUYwU3/0XSAM1Ug71EgmmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
