# __generated__ by Terraform
# Please review these resources and move them into your main configuration files.

# __generated__ by Terraform
resource "proxmox_virtual_environment_vm" "nixos_template" {
  acpi                = true
  bios                = "seabios"
  boot_order          = null
  description         = " generated by NixOS"
  hook_script_file_id = null
  keyboard_layout     = null
  kvm_arguments       = null
  mac_addresses       = []
  machine             = null
  migrate             = null
  name                = "nixos-template"
  node_name           = "pve"
  on_boot             = null
  pool_id             = null
  protection          = false
  reboot              = null
  scsi_hardware       = "virtio-scsi-single"
  started             = false
  stop_on_destroy     = null
  tablet_device       = true
  tags                = []
  template            = true
  timeout_clone       = null
  timeout_create      = null
  timeout_migrate     = null
  timeout_reboot      = null
  timeout_shutdown_vm = null
  timeout_start_vm    = null
  timeout_stop_vm     = null
  vm_id               = 103
  agent {
    enabled = true
    timeout = "15m"
    trim    = false
    type    = null
  }
  disk {
    aio               = "io_uring"
    backup            = true
    cache             = "none"
    datastore_id      = "local-lvm"
    discard           = "ignore"
    file_format       = "raw"
    file_id           = null
    interface         = "virtio0"
    iothread          = false
    path_in_datastore = "base-103-disk-0"
    replicate         = true
    serial            = null
    size              = 4
    ssd               = false
  }
  initialization {
    datastore_id         = "local-lvm"
    interface            = "ide2"
    meta_data_file_id    = null
    network_data_file_id = null
    type                 = null
    user_data_file_id    = null
    vendor_data_file_id  = null
    ip_config {
      ipv4 {
        address = "dhcp"
        gateway = null
      }
    }
  }
  memory {
    dedicated      = 1024
    floating       = 0
    hugepages      = null
    shared         = 0
  }
  network_device {
    bridge       = "vmbr0"
    disconnected = false
    enabled      = true
    firewall     = true
    mac_address  = "BC:24:11:08:D4:87"
    model        = "virtio"
    mtu          = 0
    queues       = 0
    rate_limit   = 0
    trunks       = null
    vlan_id      = 0
  }
  operating_system {
    type = "l26"
  }
  serial_device {
    device = "socket"
  }
}
